# -*- coding: utf-8 -*-
"""me-or-bts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V2LxgYwtfhzn-nYD4F8u7EPZ0yx-riYb
"""

'''
Assignment: Image Classification with Convolutional Neural Networks
You will build and train a Convolutional neural network (CNN) that can distinguish between images
of your own face and another class (e.g., a friend, a celebrity, or a set of random faces).
This project is designed to help you apply concepts of image classification using deep learning.
'''

#Try to get 25 selfies (myself) vs bts category (25 images), image of BTS members will be provided in repo

from google.colab import drive
drive.mount('/content/drive')

#If running on Colab, I encourage you to first save the dataset in your Google Drive

!ls -F '/content/drive/MyDrive/assign5'

#Change the 'path' to the document appropriately (you can 'copy path' under Colab environment)

#Save your dataset into two different folders (train and validation). Within those folders save BTS images and your selfie images separaetly

#Ex) /validation/bts, /validation/your-name, /train/bts, /train/your-name

from keras import layers
from keras import models
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)))
model.add (layers.MaxPooling2D((2, 2)))
model.add (layers.Conv2D(64, (3, 3), activation='relu'))
model.add (layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add (layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(128, (3, 3), activation='relu'))
model.add (layers.MaxPooling2D((2, 2)))
model.add (layers. Flatten())
model.add (layers.Dense(512, activation='relu'))
model.add(layers.Dense(1, activation='sigmoid'))

model.summary()

from keras import optimizers
model.compile(loss='binary_crossentropy',optimizer=optimizers.RMSprop(learning_rate=1e-4), metrics=['acc'])

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale=1./255) #rescale all images by 1/255
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory('/content/drive/MyDrive/assign5/train',
                                                    target_size=(150,150),
                                                    batch_size=20,
                                                    class_mode='binary')
validation_generator = test_datagen.flow_from_directory('/content/drive/MyDrive/assign5/validation',
                                                    target_size=(150,150),
                                                    batch_size=20,
                                                    class_mode='binary')

#Again, change the path to document appropriately.

import tensorflow as tf
tf.test.gpu_device_name()

history = model.fit(train_generator,
                              steps_per_epoch=100,
                              epochs=30,
                              validation_data=validation_generator,
                              validation_steps=50)

import matplotlib.pyplot as plt
acc = history.history['acc']
val_acc = history.history['val_acc']
loss = history.history['loss']
val_loss = history.history['val_loss']
epochs = range(1, len(acc) + 1)
plt.plot(epochs, acc, 'bo', label='Training acc'), plt.plot(epochs, val_acc, 'b', label='Validation acc'), plt.title( 'Training and validation accuracy')
plt.legend()
plt.figure()
plt.plot(epochs, loss, 'bo', label='Training loss'), plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.legend ()
plt.show()

datagen = ImageDataGenerator(rotation_range=40,
                             width_shift_range=0.2,
                             height_shift_range=0.2,
                             shear_range=0.2,
                             zoom_range=0.2,
                             horizontal_flip=True,
                             fill_mode='nearest')

import os
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
from tensorflow.keras.utils import array_to_img

train_jae_dir = '/content/drive/MyDrive/assign5/train/your-name'

#get list of file names in train cats folder
fnames =[os.path.join(train_jae_dir, fname) for fname in os.listdir(train_jae_dir)]

#we pick one cat image

img_path = fnames[3]

#read the image and resize it
img = load_img(img_path, target_size=(150,150))

#convert it to a numpy array with shape (150,150,3)
x = img_to_array(img)

#reshape it to (1,150,150,3)
x=x.reshape((1,) + x.shape)

# the .flow() command below generates batches of randomly transformed images.
# it wil loop indefinitely, so we need to break the loop at some point

i=0
for batch in datagen.flow(x, batch_size=1):
  plt.figure(i)
  imgplot = plt.imshow(array_to_img(batch[0]))
  i += 1
  if i % 4 ==0:
    break

  plt.show()

#dropout to see if it's extremly fitted, to avoid overfitting / pruning

model = models. Sequential()
model.add (layers.Conv2D(32, (3, 3), activation='relu', input_shape=(150, 150, 3)))
model.add (layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (3, 3), activation='relu'))
model.add (layers.MaxPooling2D((2, 2)))
model.add (layers.Conv2D(128, (3, 3), activation='relu'))
model.add (layers.MaxPooling2D((2, 2)))
model.add (layers.Conv2D(128, (3, 3), activation='relu'))
model.add (layers.MaxPooling2D((2, 2)))
model.add (layers. Flatten())
model.add (layers. Dropout (0.5))
model.add (layers.Dense(512, activation='relu'))
model.add (layers.Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy',
optimizer=optimizers.RMSprop(learning_rate=1e-4), metrics=['acc'])

from tensorflow.keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(
  rescale=1./255,
  rotation_range=40,
  width_shift_range=0.2,
  height_shift_range=0.2,
  shear_range=0.2,
  zoom_range=0.2,
  horizontal_flip=True)

# Note that the validation data should not be augmented!
test_datagen = ImageDataGenerator(rescale=1./255)
train_generator = train_datagen.flow_from_directory(
# This is the target directory
'/content/drive/MyDrive/assign5/train',
# All images will be resized to 150x150
target_size=(150, 150), batch_size=20,
# Since we use binary_crossentropy loss, we need binary labels
class_mode= 'binary')
validation_generator = test_datagen.flow_from_directory(
'/content/drive/MyDrive/assign5/validation',
target_size=(150, 150) , batch_size=20, class_mode='binary')

history = model.fit(
    train_generator,
    steps_per_epoch=50,
    epochs=100,
    validation_data=validation_generator,
    validation_steps=50
)

model.save('assign5.h5')

model.save('assign5.keras')

acc = history.history['acc']
val_acc = history.history['val_acc']
loss = history.history['loss']
val_loss = history.history['val_loss']

epochs = range(len(acc))

plt.plot(epochs, acc, 'bo', label='Training acc')
plt.plot(epochs, val_acc, 'b', label='Validation acc')
plt.title('Training and validation accuracy')
plt.legend()

plt.figure()

plt.plot(epochs, loss, 'bo', label='Training loss')
plt.plot(epochs, val_loss, 'b', label='Validation loss')
plt.title('Training and validation loss')
plt.legend()

plt.show()

from tensorflow import keras
model = keras.models.load_model('/content/assign5.keras')

from tensorflow.keras.utils import load_img, img_to_array
import numpy as np

img = load_img('/content/your-other-image-for-prediction.jpeg', target_size=(150,150))

img_array = img_to_array(img)

img_array = np.expand_dims(img_array, axis=0)

img_array = img_array / 255.0

prediction = model.predict(img_array)

#print prediction
if prediction[0] < 0.5:
  print("He might be a BTS member")
else:
  print("He is your-name")

#load the image that's not been used for training or validation.

prediction = model.predict(img_array)

score = prediction[0][0]

if score < 0.5:
    confidence = (1 - score) * 100
    print(f"I am {confidence:.2f}% confident that he is a BTS member")
else:
    # If the score is 0.95, it's 95% sure it's J
    confidence = score * 100
    print(f"I am {confidence:.2f}% confident that he is your-name")